// AUTO-GENERATED by scripts/generate-galleries.mjs — do not edit by hand.
// Rebuild with: npm run galleries

export type GalleryItem = { src?: string; type: 'image' | 'video' }

export type GalleryGroup = { folder: string; label: string; items: GalleryItem[] }

export const galleriesData: Record<string, GalleryGroup[]> = {
  "dav-rohini-mun": [
    {
      "folder": "images/mun",
      "label": "Placard Designs",
      "items": [
        {
          "src": "/images/mun/14.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/15.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/24.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/25.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/aippm.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/BIFDBD.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/bruh.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/coming.png",
          "type": "image"
        },
        {
          "src": "/images/mun/commitee.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/DJVBIDJNV.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/DMDMD.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/dsgl.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/efkhfe.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/FDFDDF.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/ggggggggg.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/GJDFGKJDFHG.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/gjg.png",
          "type": "image"
        },
        {
          "src": "/images/mun/GNIRD.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/hfviefh.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/HJJJHJJ.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/hlhllllllll.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/hrthrth.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/I.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/ip.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/iyiiy.png",
          "type": "image"
        },
        {
          "src": "/images/mun/jdldjd.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/jgjggigiu.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/JGJGJG.png",
          "type": "image"
        },
        {
          "src": "/images/mun/jin.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/jjh.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/jsbfo.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/JULY.png",
          "type": "image"
        },
        {
          "src": "/images/mun/JULYFF.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/LOK SABHA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/LOK SABHA1.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/MAIN FILE.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/MLMLM.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/NBNB.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/NEW.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/ojjpjp.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/page2.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/PAGE3.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/page4.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/page5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/puneet.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/SDGIDI.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/secretariat.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/senior.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/SOON.png",
          "type": "image"
        },
        {
          "src": "/images/mun/students.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/SXSJGS.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/tyutut.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/UNHRC.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/uututu.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun/wast1.png.webp",
          "type": "image"
        }
      ]
    },
    {
      "folder": "images/mun-brochure",
      "label": "Brochure",
      "items": [
        {
          "src": "/images/mun-brochure/03.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/12.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/aarushi.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB1.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB2.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB3.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB4.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB6.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB7.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/EB8.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/hansuja.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/hanusja.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/incharge.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 1.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 2.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 3.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 4.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 5.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 6.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 7.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/page 8.png",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/patron.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-brochure/register.png",
          "type": "image"
        }
      ]
    },
    {
      "folder": "images/mun-certificates",
      "label": "Certificates",
      "items": [
        {
          "src": "/images/mun-certificates/1.png",
          "type": "image"
        },
        {
          "src": "/images/mun-certificates/2.png",
          "type": "image"
        },
        {
          "src": "/images/mun-certificates/3.png",
          "type": "image"
        }
      ]
    },
    {
      "folder": "images/mun-placards",
      "label": "Country Placards",
      "items": [
        {
          "src": "/images/mun-placards/aarusih.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Adv. A. M. Ariff.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/AFRICAN REPUBLIC.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/ALGERIA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/aman yadav.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/AMBIKA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/AMIT.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/ANIRUDH.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/ANISKA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/ANUPRIYA.png",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/argentina.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/BELGIUM.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/caicaturist.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/CANADA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/CAPTAIN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/CHADHA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/CHANCHAL JAISWAL.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/CHAUHAN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/CHINA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/CUBA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/dalal.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/DENMARK.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/director.png",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/EGYPT.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/FIJI.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/FINLAND.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/GADKARI.png",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/GAMBHIR.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/GARIMA school.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/garima.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/GERMANY.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/GOPAL.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/GREECE.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/HANS RAJ.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/hansuja.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Haridas, Ms. Ramya.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/HARSH VARDHAN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/HARSHITA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/HIMANTA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/HIRAL DESAI.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/ICELAND.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/india.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/ISRAEL.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Jaishankar, Dr Subhramanyam.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/JAISHANKAR.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/JAPAN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Journalist.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/KEJRIWAL.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/kush.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/lipka.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MAIN PAGE.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MALAYSIA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MALDIVES.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MANMOHAN SINGH.png",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MANN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MANYA KHURANA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/mayank sir.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MODI.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/MYANMAR.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/NABA KUMAR.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/NETHERLANDS.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/NEW ZEALAND.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/NIHARIKA GUPTA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/NIRMALA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/NITIN JAIRAM.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/NORWAY.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/OWAISI.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/PAKISTAN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/PARI GOYAL.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/PHILLIPPINES.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/photo.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/PIYUSH.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/POLAND.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/POOJA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/POTUGAL.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/pragya.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/PRASAD.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/QATAR.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/RAHUL.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/RAJE.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Reddy, Shri P.V. Midhun.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/RIJJU.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/roy.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SANJAY SINGH.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Sarangi, Smt. Aparajita.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Satyanarayana, Shri M V V.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SCINIDA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SHAH.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SHAHSI.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SHREYA JHA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SINGAPORE.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Singh, Shri Rajnath.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SONIA.png",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SPAIN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SRI LANKA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Surya, Shri L.S. Tejasvi.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/SWEDEN.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Syed Imtiaz Jaleel, Shri.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/TEWARI.png",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/THACKRAY.png",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Thakur, Shri Anurag Singh.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/TURKEY.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/UAE.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/unga chairperson.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/unga vice chair.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/upadhay.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/USA.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/VAIBHAV.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/Vanga, Smt. Geetha Viswanath.png.webp",
          "type": "image"
        },
        {
          "src": "/images/mun-placards/YOGI.png.webp",
          "type": "image"
        }
      ]
    },
    {
      "folder": "images/secretariat",
      "label": "Secretariat",
      "items": [
        {
          "src": "/images/secretariat/aarushi.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/anirudh.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/anishka.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/chanchal.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/garima.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/hansuja.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/harshita.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/hiral.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/kripa.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/lipika.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/manvi.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/manya.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/niharika.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/pari.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/pooja.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/shreya.png.webp",
          "type": "image"
        },
        {
          "src": "/images/secretariat/vaibhav.png.webp",
          "type": "image"
        }
      ]
    }
  ],
  "rudra-the-street-play-society": [
    {
      "folder": "images/auditions-2025-26",
      "label": "Auditions 2025-26",
      "items": [
        {
          "src": "/images/auditions-2025-26/1.jpg",
          "type": "image"
        },
        {
          "src": "/images/auditions-2025-26/2.jpg",
          "type": "image"
        },
        {
          "src": "/images/auditions-2025-26/3.jpg",
          "type": "image"
        },
        {
          "src": "/images/auditions-2025-26/auditions showreel.mp4",
          "type": "video"
        }
      ]
    },
    {
      "folder": "images/canva-insta-stories",
      "label": "Canva & Insta Stories",
      "items": [
        {
          "src": "/images/canva-insta-stories/1.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/2.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/3.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/4.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/6.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/7.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/8.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/9.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/10.png.webp",
          "type": "image"
        },
        {
          "src": "/images/canva-insta-stories/11.jpg",
          "type": "image"
        }
      ]
    },
    {
      "folder": "images/core-team-introduction-rudra",
      "label": "Core Team Intro",
      "items": [
        {
          "src": "/images/core-team-introduction-rudra/1.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/2.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/3.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/4.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/5.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/6.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/7.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/8.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/9.jpg",
          "type": "image"
        },
        {
          "src": "/images/core-team-introduction-rudra/coreteamintroduction-showreel.mp4",
          "type": "video"
        }
      ]
    },
    {
      "folder": "images/event highlights-spardha",
      "label": "Spardha Highlights",
      "items": [
        {
          "src": "/images/event highlights-spardha/1.jpg",
          "type": "image"
        },
        {
          "src": "/images/event highlights-spardha/2.jpg",
          "type": "image"
        },
        {
          "src": "/images/event highlights-spardha/spardha-showreel.mp4",
          "type": "video"
        },
        {
          "src": "/images/event highlights-spardha/spardha-showreel.mp5",
          "type": "video"
        }
      ]
    },
    {
      "folder": "images/event special highlights-shor",
      "label": "Shor Highlights",
      "items": [
        {
          "src": "/images/event special highlights-shor/1.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/2.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/3.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/4.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/6.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/7.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/8.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/9.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/10.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/11.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/12.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/13.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/14.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/15.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/16.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/17.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/18.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/19.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/20.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/21.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/22.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/23.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/24.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/25.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/26.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/27.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/28.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/29.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/31.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/32.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/33.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/34.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/35.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/36.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/37.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/38.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/39.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/40.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/41.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/42.png.webp",
          "type": "image"
        },
        {
          "src": "/images/event special highlights-shor/shor.mp4",
          "type": "video"
        }
      ]
    },
    {
      "folder": "images/farewell-2024-25",
      "label": "Farewell 2024-25",
      "items": [
        {
          "src": "/images/farewell-2024-25/1.jpg",
          "type": "image"
        },
        {
          "src": "/images/farewell-2024-25/2.jpg",
          "type": "image"
        },
        {
          "src": "/images/farewell-2024-25/3.jpg",
          "type": "image"
        },
        {
          "src": "/images/farewell-2024-25/4.jpg",
          "type": "image"
        },
        {
          "src": "/images/farewell-2024-25/5.jpg",
          "type": "image"
        },
        {
          "src": "/images/farewell-2024-25/6.jpg",
          "type": "image"
        },
        {
          "src": "/images/farewell-2024-25/7.jpg",
          "type": "image"
        },
        {
          "src": "/images/farewell-2024-25/farewell-2024-25-showreel.mp4",
          "type": "video"
        }
      ]
    }
  ],
  "merchandise": [
    {
      "folder": "images/merchandise",
      "label": "Merchandise",
      "items": [
        {
          "src": "/images/merchandise/1.png.webp",
          "type": "image"
        },
        {
          "src": "/images/merchandise/2.png.webp",
          "type": "image"
        },
        {
          "src": "/images/merchandise/3.png.webp",
          "type": "image"
        },
        {
          "src": "/images/merchandise/4.png.webp",
          "type": "image"
        },
        {
          "src": "/images/merchandise/5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/merchandise/6.png.webp",
          "type": "image"
        }
      ]
    }
  ],
  "poster": [
    {
      "folder": "images/poster",
      "label": "Posters",
      "items": [
        {
          "src": "/images/poster/poster.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster1.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster2.jpg",
          "type": "image"
        },
        {
          "src": "/images/poster/poster3.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster4.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster6.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster7.jpg",
          "type": "image"
        },
        {
          "src": "/images/poster/poster8.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster9.jpg",
          "type": "image"
        },
        {
          "src": "/images/poster/poster10.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster11.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster12.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster13.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster14.png.webp",
          "type": "image"
        },
        {
          "src": "/images/poster/poster15.png.webp",
          "type": "image"
        }
      ]
    }
  ],
  "youtube-thumbnails": [
    {
      "folder": "images/youtube-thumbnails",
      "label": "Thumbnails",
      "items": [
        {
          "src": "/images/youtube-thumbnails/thumbanil5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/youtube-thumbnails/thumbnail2.png.webp",
          "type": "image"
        },
        {
          "src": "/images/youtube-thumbnails/thumbnail3.jpg",
          "type": "image"
        },
        {
          "src": "/images/youtube-thumbnails/thumbnail4.png.webp",
          "type": "image"
        },
        {
          "src": "/images/youtube-thumbnails/thumbnail6.png",
          "type": "image"
        },
        {
          "src": "/images/youtube-thumbnails/thumbnail7.png.webp",
          "type": "image"
        },
        {
          "src": "/images/youtube-thumbnails/thumbnail8.jpg",
          "type": "image"
        }
      ]
    }
  ],
  "art-illustrations": [
    {
      "folder": "images/anime-fan-illustrations",
      "label": "Illustrations",
      "items": [
        {
          "src": "/images/anime-fan-illustrations/anime1.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime2.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime3.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime4.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime5.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime6.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime7.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime8.png.webp",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime9.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime10.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime11.png.webp",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/anime12.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/illustation6.jpg.webp",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/illustration2.jpg.webp",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/illustration3.jpg",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/illustration4.jpg.webp",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/illustration5.png.webp",
          "type": "image"
        },
        {
          "src": "/images/anime-fan-illustrations/illustrattion1.jpg",
          "type": "image"
        }
      ]
    }
  ],
  "personal-edits-and-reels": [
    {
      "folder": "videos",
      "label": "Reels & Posts",
      "items": [
        {
          "src": "/videos/personal project 8.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video 5 (online-video-cutter.com).mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 1.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 2.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 3.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 4.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 6 (online-video-cutter.com).mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 9.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 10 .mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 11.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 12.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 13.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video project 14.mp4",
          "type": "video"
        },
        {
          "src": "/videos/personal video projet 7.mp4",
          "type": "video"
        }
      ]
    }
  ]
}

export const galleriesTotals: Record<string, number> = {
  "dav-rohini-mun": 209,
  "rudra-the-street-play-society": 79,
  "merchandise": 6,
  "poster": 16,
  "youtube-thumbnails": 7,
  "art-illustrations": 18,
  "personal-edits-and-reels": 14
}
